#! /usr/bin/env bash
#

# set script to exit if a command fails
set -e

# set pipelines to return failure if any command errors
set -o pipefail

# $PREFIX and $LIBDIR are set during installation of i3lock-next
PREFIX=/usr/local
LIBDIR=/lib

# display help text then exit (on -h or --help flags as arg 1)
if [[ ${1} == "-h" ]] || [[ ${1} == "--help" ]]; then
    cat <<EOF
Usage: i3lock-next [-h|--help] [prompt] [font] [size]

Options:
    -h, --help  Display this help text.

    prompt      Prompt string to display, default is none.

    font        Font to to use, default is Sans.

    size        Size of font, default is 18.

EOF
    exit
fi

# set user-defined font and fontsize or use default
_prompt=${1:-}
_font=${2:-Sans}
_size=${3:-18}

# set script to treat unset variables as an error
set -u

# find user-defined fonts
_font=$(fc-match "${_font}" -f "%{file}\n")
_font=${_font%.*}

# define name for screenshot taken with i3lock-next-helper
readonly _random=${RANDOM}
readonly _image="/tmp/tmp.${_random}.png"

# make sure ${_image} is always deleted on exit
trap 'rm -f ${_image}' EXIT

# call i3lock-next-helper (variable to keep lines below 72 characters)
_i3lock_next_helper=${PREFIX}/${LIBDIR}/i3lock-next/i3lock-next-helper
$_i3lock_next_helper ${_image} "${_font}"/"${_size}" "${_prompt}"

# now call i3lock (should have i3lock-color installed)
#  - with custom colours (such as fully transparent text - text is
#    dealt with by i3lock-next-helper)
#  - with options -e and -n so i3lock-color ignores empty passwords
#    and doesn't fork
i3lock -n -e                    \
    --textcolor=00000000        \
    --linecolor=00000000        \
    --keyhlcolor=ffffff80       \
    --separatorcolor=22222260   \
    \
    --insidecolor=0000001c      \
    --insidevercolor=ffffff1c   \
    --insidewrongcolor=ffffff1c \
    \
    --ringcolor=0000001c        \
    --ringvercolor=ffffff00     \
    --ringwrongcolor=ffffff55   \
    \
    -i ${_image}
